django1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include ("inicio.urls"))
]

inicio/urls.py
from django.urls import path
from inicio.views import  mi_vista, inicio, vista_datos1, primer_template, segundo_template,crear_auto

app_name = "inicio"

urlpatterns = [
    path("mi-vista", mi_vista, name="mi_vista"),
    path("", inicio, name="inicio"),
    path("vista-datos1/<nombre>/", vista_datos1, name="vista_datos1"),
    path("primer-template/", primer_template, name="primer_template"),
    path("segundo-template/", segundo_template, name="segundo_template"),
    path("crear-auto/<marca>/<modelo>/<anio>/", crear_auto, name="crear_auto"),
]
 

inicio/models.py
from django.db import models


class Auto(models.Model):
    marca = models.CharField(max_length=20)
    modelo = models.CharField(max_length=20)
    anio = models.IntegerField()

    def __str__(self):
        return f"{self.modelo} {self.anio}"

inicio/views.py
from django.http import HttpResponse
from django.template import Template, Context, loader
from datetime import datetime
from django.shortcuts import render
from inicio.models import Auto

def mi_vista(request):
    return HttpResponse("hola soy la vista")

def inicio(request):
    # return HttpResponse("<h1>soy la pantalla de inicio <h1>")
    return render(request, "inicio/index.html")

def vista_datos1(request, nombre):
    nombre_mayuscula = nombre.upper()
    return HttpResponse(f"hola {nombre_mayuscula}!!")

def primer_template(request):

    with open(r"templates\primer_template.html") as archivo_del_template:
        template = Template(archivo_del_template.read())

    Contexto = Context()

    redender_template = template.render(Contexto)

    return HttpResponse(redender_template)


def segundo_template(request):

    fecha_actual = datetime.now()
    datos = {"fecha_actual": fecha_actual,
             "numeros": list(range(1,11))
    }

    # v1
    # archivo_del_template = open(r"templates\segundo_template.html")
    # template = Template(archivo_del_template.read())
    # archivo_del_template.close()
    # Contexto = Context(datos)
    # redender_template = template.render(Contexto)

    # v2
    # template = loader.get_template("segundo_template.html")
    # render_template = template.render(datos)
    # return HttpResponse(render_template)

    #v3
    return render(request, "inicio/segundo_template.html", datos) 

def crear_auto(request, marca, modelo, anio):

    auto = Auto(marca=marca, modelo=modelo, anio=anio)
    auto.save()
    return render(request, "inicio/creacion_auto_correcta.html", {"auto": auto})

inicio/templates/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %} 
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <a class="btn btn-primary" href="#signup">Sign Up</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">soy la pantalla de inicio</h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

inicio/templates/inicio/creacion_auto_correcta.html
{% extends "base.html" %}

{% block title_head %}
creacion de auto
{% endblock title_head %}

{% block h1_header %}
se creo el auto {{auto.id}} {{auto.marca}} correctamente!
{% endblock h1_header %}

inicio/templates/inicio/index.html
{% extends "base.html" %}

{% block title_head %}
inicio
{% endblock title_head %}

{% block h1_header %}
soy la pantalla de inicio
{% endblock h1_header %}

inicio/templates/inicio/segundo_template.html
{% extends "inicio/index.html" %}
{% load  static %} 
{% block h1_header %}segundo Template{% endblock h1_header %}
{% block main %}
<h2>{{fecha_actual}}</h2> 
<ul>
    <li>esto es una li de ul</li> 
</ul>
<ol>
    <li>esto es una li de ol</li>
</ol>
<p>Listado</p>
<ul>
    {% for num in numeros %}
    {% if num > 5 %}
    <li>{{num}}</li>
    {% elif num == 5%}
    <li>soy el mejor numero ... el 5</li>
    {% else %}
    <Li>soy menor a 5</Li>
    {% endif %}
    {% endfor %}    
</ul>
<img src={% static "assets/img/testimonials-3.jpg" %} alt="">
{% endblock main %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %} 
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head %}
            template base
            {% endblock title_head %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
         {% block link_stylesheet_head %}
         <link href={% static "css/styles.css" %} rel="stylesheet" />
         {% endblock link_stylesheet_head %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url "inicio:inicio" %}>Inicio</a>
                <a class="navbar-brand" href={% url "inicio:primer_template" %}>Primer Template</a>
                <a class="navbar-brand" href={% url "inicio:segundo_template" %}>Segundo Template</a>
                {% comment "" %}<a class="btn btn-primary" href="#signup">Sign Up</a>{% endcomment %}
            </div>
        </nav>
        <!-- Masthead-->
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}soy el base{% endblock h1_header %}
                            </h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        <main>
            {% block main %}{% endblock main %}
        <main>
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/primer_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        pepe corre solo
    <h1>    
</body>
</html>